### ISSUE TITLE
Changes to all conference/all league teams

### ISSUE THREAD

**Issue by mblitz** [akeaswaran/FootballCoach-iOS#20]
Currently the all conference and all league teams do not include defensive players or offensive linemen. Are individual OL and individual defensive stats kept?

**Comment by akeaswaran** [comment]
The game currently doesn't keep track of stats for offensive linemen or defensive players. I've been seeing a lot of requests for these though, so I may add them in a future version.

**Comment by Drwoody77** [comment]
Defensive players and stats would be awesome

**Comment by akeaswaran** [comment]
Defensive stats are being added in #32.
