### ISSUE TITLE
"Start Recruiting" button not showing.

### ISSUE THREAD

**Issue by rmitchellnet** [akeaswaran/FootballCoach-iOS#22]
I've finished a season and after hitting Start Recruiting on the news/schedule page, the Start Recruiting button above the View Mock Draft button isn't showing. Not sure if this is because of the number of players leaving messing up the layout or if I'm just missing something... but it's preventing me from continuing.

This is on an iPhone SE running iOS 10.0.2

![img_0396](https://cloud.githubusercontent.com/assets/342337/19708805/2d6910b4-9ad6-11e6-9ca8-f4980d8cf3d3.PNG)

**Comment by akeaswaran** [comment]
Try scrolling on the area containing all the buttons to make things available. This bug occurs because the view containing the players' details is bigger than expected, so it squishes the buttons view and appears on top of it.

**Comment by rmitchellnet** [comment]
Ah thanks, I hesitated to post this knowing it would be something dumb!
