### ISSUE TITLE
CBC recruiting next button not showing up

### ISSUE THREAD

**Issue by pennblade** [akeaswaran/FootballCoach-iOS#34]

**Comment by pennblade** [comment]
I cannot get out of the recruiting phase. I used 100% of my actions and recruited every position I needed but the next and done buttons will not highlight. What am I doing wrong?

**Comment by akeaswaran** [comment]
If you tap to dismiss all of the tutorial bubbles, then you'll be allowed to advance. The original intention of this was to help users understand how recruiting (and the transfer portal, since this occurs there too) works before advancing through the mode. This will be fixed in a future release.
